name = "mce-certification"
compatibility_date = "2024-01-15"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "mce-certification-db"
database_id = "c7e8fbca-0920-4174-a7f7-67ea3aa5411c"
